### ISSUE TITLE
Command queues

### ISSUE THREAD

**Issue by i8beef** [jlynch630/Harmony.NET#11]
I saw you had a note about commands executed in sequence and 400ms spacing or the harmony would ignore them or something? When you get a chance can you elaborate on that? I'm thinking like the case of someone sending multiple commands not through that interface, but directly one by one and going faster than this rate. Whats the reasoning for the rate limiting there, and if there's a limitation, would it make sense to introduce some sort of queueing to command message sending?

**Comment by sirmeili** [comment]
This was not an issue in the XMPP implementation which is why I think @i8beef is asking. You could send 1ms apart, but depending on network traffic they might arrive in the wrong order.

**Comment by jlynch630** [comment]
Yeah so the more I think about it the more I'm thinking there's a chance
that it's my DirecTV box that's struggling and not the harmony itself. I'll
keep testing

On Dec 19, 2018 8:11 PM, "Frank Thompson" <notifications@github.com> wrote:

This was not an issue in the XMPP implementation which is why I think
@i8beef <https://github.com/i8beef> is asking. You could send 1ms apart,
but depending on network traffic they might arrive in the wrong order.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/jlynch630/Harmony.NET/issues/11#issuecomment-448860212>,
or mute the thread

**Comment by i8beef** [comment]
Neat, ok. Yeah I was wondering about it for that reason. The WebSocket implementation COULD BE DIFFERENT, but it seemed odd, and when I was testing with your library it DID seem like it had more lag... but when I saw this I wasn't sure if it was the WebSocket or this artificial limiter.
