### ISSUE TITLE
Connection to myharmony.com?

### ISSUE THREAD

**Issue by bluewalk** [jlynch630/Harmony.NET#18]
I noticed that the library is connecting to either `*.myharmony.com` or `*.dhg.myharmony.com`, any idea where and why this is happening? It only appears the first minute when doing a discovery.

![image](https://user-images.githubusercontent.com/6522477/50684022-6caa4800-1014-11e9-8de1-864df2364ded.png)

Upon checking the IP addresses (`34.192.104.176` and `52.7.206.211` for now):

![image](https://user-images.githubusercontent.com/6522477/50684083-98c5c900-1014-11e9-9f66-f647b890a955.png)

**Comment by phen0mX** [comment]
Just had a little look and there are no packets leaving the local network on my end.
Even with the discovery running constantly. The only reference to myharmony I found was:
`Connect(string hostname, string hubRemoteId) {` 
`string FullUrl = $"ws://{hostname}:8088/?domain=svcs.myharmony.com&hubId={hubRemoteId}";
return base.Connect(FullUrl); }`

**Comment by bluewalk** [comment]
That's exactly why I was surprised as well. I had a good look at my own code as well but don't see any reference there either.

**Comment by jlynch630** [comment]
Are you sure you aren't making any calls to `GetUserInfo` or `GetInfoForProvider`? Those would contact myharmony.com

**Comment by phen0mX** [comment]
@jlynch630 Is right.
Those call the logitech myharmony api.
The reason it is non obvious is because those urls are retrieved from HubSync.
See:
`{"contentDeviceHost":"https://content.dhg.myharmony.com/1.0/Device;{deviceProfileUri}","contentImageHost":"https://d1tk8oqnnsddt5.cloudfront.net/1.0/station/{stationId}/image;maxX=40;maxY=40","contentServiceHost":"https://content.dhg.myharmony.com/1.0/Service/{providerId}","contentUserHost":"https://content.dhg.myharmony.com/1.0/User;{userProfileUri}","householdUserProfileUri":"svcs.myharmony.com/res//household/5296434-3QExG1PxyqChDncMaDvnn0Nl68thwhv12pWApuqxJQg=/user/default"}`
And that's why I didn't see any traffic.

**Comment by bluewalk** [comment]
Ah that's why, it is indeed requesting user info upon successful discovery. Great job on finding this, case closed :)
